version: "3.7"
services:

    app:
        build: .
        container_name: app-laravel        
        volumes:
            - .:/var/www
        networks:
            - app-network
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306
        environment: 
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx-laravel
        restart: always
        tty: true
        entrypoint: dockerize -template ./.docker/nginx/.nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off";
        environment: 
            - HOST=APP
            - PORT=9000
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app        
        
    
    db:
        build: .docker/db
        command: --innodb-use-native-aio=0
        container_name: db-laravel
        restart: always
        tty: true
        ports:
            - "33006:3306"
        # volumes:
        #     - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root     
        networks:
            - app-network
        
    redis: 
        container_name: redis-laravel
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network
                


networks:
    app-network:
        driver: bridge

