apiVersion: v1
kind: Service
metadata:
  name: mysql-service # NOME DO MEU SERVICE " DB_HOST=mysql-service " do arquivo  .ENV
spec:
  selector:
    app:  mysql-server
    tier: db
  ports:
  - port: 3306
  clusterIP: None
